CREATE TABLE public.organization (
    organization_id SERIAL PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    description TEXT NOT NULL,
    contact_email VARCHAR(255) NOT NULL,
    logo_filename VARCHAR(255) NOT NULL
);

-----------------------------------------------------
-----------------------------------------------------
INSERT INTO public.organization (name, description, contact_email, logo_filename)
VALUES 
('BrightFuture Builders', 'A nonprofit focused on improving community infrastructure through sustainable construction projects.', 'info@brightfuturebuilders.org', 'brightfuture-logo.png'),
('GreenHarvest Growers', 'An urban farming collective promoting food sustainability and education in local neighborhoods.', 'contact@greenharvest.org', 'greenharvest-logo.png'),
('UnityServe Volunteers', 'A volunteer coordination group supporting local charities and service initiatives.', 'hello@unityserve.org', 'unityserve-logo.png');

-----------------------------------------------------
-----------------------------------------------------
-- 1. Create Service Project Table 
CREATE TABLE public.service_project (
    project_id INT GENERATED BY DEFAULT AS IDENTITY,
    organization_id INT NOT NULL,
    project_title CHARACTER VARYING(150) NOT NULL,
    project_description TEXT NOT NULL,
    project_location CHARACTER VARYING(100) NOT NULL,
    project_date DATE NOT NULL,
    CONSTRAINT service_project_pk PRIMARY KEY (project_id),
    CONSTRAINT fk_organization FOREIGN KEY (organization_id)
        REFERENCES public.organization (organization_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

-- 2. Insert 15 Service Projects (5 per existing organization)

-- Projects for BrightFuture Builders (ID 1)
INSERT INTO public.service_project (organization_id, project_title, project_description, project_location, project_date)
VALUES 
(1, 'Roof Repair Initiative', 'Helping low-income families fix leaking roofs.', 'West District', '2026-06-15'),
(1, 'Community Center Paint', 'Refreshing the local youth center exterior.', 'Downtown', '2026-06-22'),
(1, 'Wheelchair Ramp Build', 'Constructing access ramps for senior citizens.', 'Eastside', '2026-07-05'),
(1, 'Playground Restoration', 'Refurbishing wooden structures at Central Park.', 'Central Park', '2026-07-12'),
(1, 'Greenhouse Assembly', 'Building a sustainable greenhouse for a local school.', 'Northside Academy', '2026-08-01');

-- Projects for GreenHarvest Growers (ID 2)
INSERT INTO public.service_project (organization_id, project_title, project_description, project_location, project_date)
VALUES 
(2, 'Seedling Distribution', 'Providing organic seeds to urban residents.', 'City Plaza', '2026-06-10'),
(2, 'Composting Workshop', 'Teaching the basics of soil health and composting.', 'Community Garden', '2026-06-20'),
(2, 'Irrigation System Setup', 'Installing water-saving systems for small farms.', 'South Valley', '2026-07-08'),
(2, 'Harvest Festival Prep', 'Organizing the annual local produce market.', 'Market Square', '2026-07-22'),
(2, 'Vertical Garden Install', 'Setting up herb gardens in high-density areas.', 'Apartment Complex B', '2026-08-05');

-- Projects for UnityServe Volunteers (ID 3)
INSERT INTO public.service_project (organization_id, project_title, project_description, project_location, project_date)
VALUES 
(3, 'Emergency Food Drive', 'Sorting and packing non-perishables.', 'Unity Hall', '2026-06-05'),
(3, 'Senior Tech Support', 'Volunteers helping seniors with video calls.', 'Sunset Villa', '2026-06-18'),
(3, 'Local Park Cleanup', 'Removing litter and invasive species.', 'Riverside Park', '2026-07-15'),
(3, 'Blood Donation Drive', 'Coordinating with the local hospital for donors.', 'Civic Center', '2026-07-28'),
(3, 'Youth Mentorship Mixer', 'Connecting students with professional mentors.', 'Public Library', '2026-08-12');


-----------------------------------------------------
-----------------------------------------------------Categories table creation. 


-- 1. Create the categories table
CREATE TABLE IF NOT EXISTS public.categories (
    category_id SERIAL PRIMARY KEY,
    category_name VARCHAR(100) NOT NULL UNIQUE
);

-- 2. Create the join table for the many-to-many relationship
CREATE TABLE IF NOT EXISTS public.project_categories (
    project_id INT NOT NULL,
    category_id INT NOT NULL,
    PRIMARY KEY (project_id, category_id),
    CONSTRAINT fk_project FOREIGN KEY (project_id) REFERENCES public.service_project (project_id) ON DELETE CASCADE,
    CONSTRAINT fk_category FOREIGN KEY (category_id) REFERENCES public.categories (category_id) ON DELETE CASCADE
);

-- 3. Insert at least 3 relevant categories (matching your view)
INSERT INTO public.categories (category_name) 
VALUES 
    ('Environmental'),
    ('Educational'),
    ('Community Service'),
    ('Health and Wellness');

-- 4. Associate your existing projects with at least one category
-- (Replace '1' and '2' with actual project_ids and category_ids present in your database)
INSERT INTO public.project_categories (project_id, category_id)
VALUES 
    (1, 1), -- Associates project 1 with Environmental
    (1, 3), -- Associates project 1 with Community Service (Many-to-Many demonstration)
    (2, 2); -- Associates project 2 with Educational


-----------------------------------------------------
-----------------------------------------------------

